### ISSUE TITLE
PDF file appears corrupt

### ISSUE THREAD

**Issue by daveolker** [HewlettPackard/hpe-solutions-openshift#12]
The PDF file located here: hpe-solutions-openshift/synergy/scalable/3par/Red_Hat_OpenShift_on_HPE_Synergy_and_HPE_3PAR_StoreServ_Storage_v3.0.pdf

the header page looks corrupt, where the HPE logo is messed up and covering some text.

**Comment by dougharthpe** [comment]
Thanks Dave. Will work with our pub team to generate a new version.
